OneBitTask.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace OneBitTask.Web.Controllers
{
    public class BaseController : Controller
    {
        protected void SetSuccessMessage(string message)
        {
            this.TempData["SuccessMessage"] = message;
        }

        protected void SetErrorMessage(string message)
        {
            this.TempData["ErrorMessage"] = message;
        }

        protected void SetWarningMessage(string message)
        {
            this.TempData["WarningMessage"] = message;
        }
    }
}

OneBitTask.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using OneBitTask.Services;
using OneBitTask.ViewModels.Customer;

namespace OneBitTask.Web.Controllers
{
    public class CustomerController : BaseController
    {
        private readonly ICustomerService customerService;

        public CustomerController(ICustomerService customerService)
        {
            this.customerService = customerService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult GetTableDate(int draw = 1, int start = 0, int length = 25)
        {
            var sortColumnString = HttpContext.Request.Form["order[0][column]"].ToString();
            var sortDirectionString = HttpContext.Request.Form["order[0][dir]"].ToString();

            var tableData = this.customerService.GetTableData(draw, start, length, sortColumnString, sortDirectionString);
            return this.Json(tableData);
        }

        [HttpGet]
        public IActionResult Details([FromRoute] int id)
        {
            var model = this.customerService.GetDetails(id);
            if (model == null)
            {
                this.SetErrorMessage("Customer does not exist");
                return this.RedirectToAction(nameof(CustomerController.Index));
            }

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(AddCustomerViewModel model)
        {
            this.customerService.Create(model);

            this.SetSuccessMessage("Customer created.");
            return this.RedirectToAction(nameof(CustomerController.Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.customerService.GetEditModel(id);

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditCustomerViewModel model)
        {
            this.customerService.Update(model);
            this.SetSuccessMessage("Customer updated.");
            return this.RedirectToAction(nameof(CustomerController.Details), new { id = model.Id });
        }
        
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            this.customerService.Delete(id);
            return this.Ok("Customer deleted.");
        }

        [HttpPut]
        public IActionResult ChangeStatus(int id)
        {
            this.customerService.ChangeStatus(id);
            return this.Ok("Customer updated.");
        }
    }
}

OneBitTask.Web/Controllers/PurchaseOrderController.cs
using Microsoft.AspNetCore.Mvc;
using OneBitTask.Services;
using OneBitTask.ViewModels.PurchaseOrder;

namespace OneBitTask.Web.Controllers
{
    public class PurchaseOrderController : BaseController
    {
        private readonly IPurchaseOrderService purchaseOrderService;

        public PurchaseOrderController(IPurchaseOrderService purchaseOrderService)
        {
            this.purchaseOrderService = purchaseOrderService;
        }

        [HttpPost]
        public IActionResult Create(AddPurchaseOrderViewModel model)
        {
            this.purchaseOrderService.Create(model);
            this.SetSuccessMessage("Purchase Order added.");
            return this.RedirectToAction(nameof(CustomerController.Details), "Customer", new { Id = model.CustomerId } );
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = this.purchaseOrderService.GetEditModel(id);

            return this.View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditPurchaseOrderViewModel model)
        {
            this.purchaseOrderService.Update(model);
            this.SetSuccessMessage("Customer updated.");
            return this.RedirectToAction(nameof(CustomerController.Details), "Customer", new { id = model.CustomerId });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            this.purchaseOrderService.Delete(id);
            return this.Ok("Purchase order deleted.");
        }

        [HttpPut]
        public IActionResult ChangeStatus(int id)
        {
            this.purchaseOrderService.ChangeStatus(id);
            return this.Ok("Purchase order updated.");
        }
    }
}

OneBitTask.Web/Views/Customer/Create.cshtml
@model AddCustomerViewModel
@{
    ViewData["Title"] = "Create Customer";
}

<h2>Create Customer</h2>

<form asp-controller="Customer" asp-action="Create" method="post">
    <div class="container">
        <div class="form-group">
            <label asp-for="FirstName" class="form-check-label">First Name</label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LastName" class="form-check-label">Last Name</label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telephone" class="form-check-label">Telephone</label>
            <input asp-for="Telephone" class="form-control" />
            <span asp-validation-for="Telephone" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Sex" class="form-check-label">Sex</label>
            <select class="form-control" asp-for="Sex" asp-items="Html.GetEnumSelectList<Gender>()">
                <option selected="selected" value="">Please select</option>
            </select>
            <span asp-validation-for="Sex" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a class="btn btn-secondary" asp-controller="Customer" asp-action="Index">Back</a>
</form>

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

OneBitTask.Web/Views/Customer/Details.cshtml
@model DetailsCustomerViewModel

@{
    ViewData["Title"] = "Customer Details";
}

<div class="row">
    <div class="col-4" style="padding-right: 0px">
        <h2>@ViewData["Title"]</h2>
    </div>
    <div class="col-3" style="padding-left: 0px">
        <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary custom-btn-margin">Edit</a>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-3">
        <h3>Purchase orders</h3>
    </div>
    <div class="col-9">
        <button type="button" class="btn btn-success custom-btn-margin float-right" data-toggle="modal" data-target="#add-purchase-order-modal">Add Purchase Order</button>
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th class="text-center" scope="col">Id</th>
            <th class="text-center" scope="col">Description</th>
            <th class="text-center" scope="col">Price</th>
            <th class="text-center" scope="col">Quantity</th>
            <th class="text-center" scope="col">Total Amount</th>
            <th class="text-center" scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.PurchaseOrders.Any())
        {
            @foreach (var order in Model.PurchaseOrders)
            {
                <tr class="@(order.Status == EntityStatus.Inactive ? "inactive" : "")">
                    <td class="text-center">@order.Id</td>
                    <td class="text-center">@order.Description</td>
                    <td class="text-center">@order.Price</td>
                    <td class="text-center">@order.Quantity</td>
                    <td class="text-center">@order.TotalAmount</td>
                    <td class="table-options-group">
                        <div class="text-center">
                            <button type="button" id="@order.Id" class="btn btn-danger btn-sm delete-purchase-order-btn">Delete</button>
                            @{
                                var buttonValue = order.Status == EntityStatus.Active ? "Deactivate" : "Active";
                            }

                            <button type="button" id="@order.Id" class="btn btn-secondary btn-sm change-purchase-order-status-btn">@buttonValue</button>

                            <a asp-controller="PurchaseOrder" asp-action="Edit" asp-route-id="@order.Id" class="btn btn-secondary btn-sm" id="@order.Id">Edit</a>
                        </div>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <th colspan="6" class="text-center">No purchase orders to display</th>
            </tr>
        }
    </tbody>
</table>

@{ await Html.RenderPartialAsync("_AddPurchaseOrderModal", new AddPurchaseOrderViewModel() { CustomerId = Model.Id });}

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script src="~/js/Customer/details.js"></script>

    <script>
        CustomerDetails.init();
    </script>
}

OneBitTask.Web/Views/Customer/Edit.cshtml
@model EditCustomerViewModel
@{
    ViewData["Title"] = "Edit Customer";
}

<h2>Edit Customer</h2>

<form asp-controller="Customer" asp-action="Edit" method="post">
    <div class="container">
        <div class="form-group">
            <label asp-for="FirstName" class="form-check-label">First Name</label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LastName" class="form-check-label">Last Name</label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telephone" class="form-check-label">Telephone</label>
            <input asp-for="Telephone" class="form-control" />
            <span asp-validation-for="Telephone" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Sex" class="form-check-label">Sex</label>
            <select class="form-control" asp-for="Sex" asp-items="Html.GetEnumSelectList<Gender>()">
                <option selected="selected" value="">Please select</option>
            </select>
            <span asp-validation-for="Sex" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a class="btn btn-secondary" asp-controller="Customer" asp-action="Index">Back</a>
</form>

@section scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

OneBitTask.Web/Views/Customer/Index.cshtml
@{
    ViewData["Title"] = "Customers Index";
}

<div class="text-center">
    <h2 class="display-4">Welcome</h2>
    <p>You can view your customer data here.</p>
    <a asp-controller="Customer" asp-action="Create" class="btn btn-success">Create Customer</a>
</div>

<table id="customer-list-table" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/Customer/index.js"></script>
    <script>
        CustomerIndex.init();
    </script>
}

OneBitTask.Web/Views/Customer/_AddPurchaseOrderModal.cshtml
@model AddPurchaseOrderViewModel

<div class="modal fade" id="add-purchase-order-modal" tabindex="-1" role="dialog" aria-labelledby="add-purchase-order-modal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Purchase Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="PurchaseOrder" asp-action="Create" method="post">
                @Html.HiddenFor(x => x.CustomerId)

                <div class="modal-body">
                    <div class="container">
                        <div class="form-group">
                            <label asp-for="Description" class="form-check-label">Description</label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Price" class="form-check-label">Price</label>
                            <input asp-for="Price" id="purchase-order-price-input" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Quantity" class="form-check-label">Quantity</label>
                            <input asp-for="Quantity" id="purchase-order-quantity-input" class="form-control" />
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label class="form-check-label">Total Amount</label>
                            <input id="purchase-order-total-amount-input" value="0" disabled="disabled" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

OneBitTask.Web/Views/PurchaseOrder/Edit.cshtml
@model EditPurchaseOrderViewModel

<h2>Edit Purchase Order</h2>
<form asp-controller="PurchaseOrder" asp-action="Edit" method="post">
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.CustomerId)

    <div class="form-group">
        <label asp-for="Description" class="form-check-label">Description</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price" class="form-check-label">Price</label>
        <input asp-for="Price" id="purchase-order-price-input" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Quantity" class="form-check-label">Quantity</label>
        <input asp-for="Quantity" id="purchase-order-quantity-input" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-check-label">Total Amount</label>
        <input id="purchase-order-total-amount-input" value="@Model.TotalAmount" disabled="disabled" class="form-control" />
    </div>

    <a asp-controller="Customer" asp-action="Details" asp-route-id="@Model.CustomerId" class="btn btn-secondary" data-dismiss="modal">Back</a>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/PurchaseOrder/edit.js"></script>
    <script>
        PurchaseOrderEdit.init()
    </script>
}

OneBitTask.Web/Views/Shared/_Layout.cshtml
@{
    ViewData["AppName"] = "OneBit Portal";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    @{ await Html.RenderPartialAsync("_Styles");}
    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        @{ await Html.RenderPartialAsync("_Navbar");}
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - @ViewData["AppName"]
        </div>
    </footer>

    @{ await Html.RenderPartialAsync("_Scripts");}
    @{ await Html.RenderPartialAsync("_Toast");}

    @RenderSection("Scripts", required: false)
</body>
</html>

OneBitTask.Web/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-controller="Customer" asp-action="Index">@ViewData["AppName"]</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Customer" asp-action="Index">Customers</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

OneBitTask.Web/Views/Shared/_Scripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>

<script src="~/lib/datatables/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>

OneBitTask.Web/Views/Shared/_Styles.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
</environment>

<link rel="stylesheet" href="~/lib/datatables/dataTables.bootstrap4.min.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<link rel="stylesheet" href="~/css/site.css" />

OneBitTask.Web/Views/Shared/_Toast.cshtml
@{
    var errorMessage = TempData["ErrorMessage"];
    var successMessage = TempData["SuccessMessage"];
    var warningMessage = TempData["WarningMessage"];
    TempData["ErrorMessage"] = null;
    TempData["SuccessMessage"] = null;
    TempData["WarningMessage"] = null;
}
<script>

    @if (errorMessage != null)
    {
        @:toastr.error('@errorMessage');
        @:console.log('@errorMessage');
    }

    @if (successMessage != null)
    {
        @:toastr.success('@successMessage');
        @:console.log('@successMessage');
    }

    @if (warningMessage != null)
    {
        @:toastr.warning('@warningMessage');
        @:console.log('@warningMessage');
    }

</script>